env:
  commonjs: true
  es6: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "prettier"

extends:
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "plugin:prettier/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
overrides:
  - files:
      - "*.test.ts"
      - "*.spec.ts"
rules:
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/ban-types": off
