version: "3.4"

services:
  amazeful-twitch:
    image: amazeful-twitch
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=development
      - MONGO_INITDB_DATABASE=AmazefulDev
      - MIKRO_ORM_CLIENT_URL=mongodb://mongo:27017
      - MIKRO_ORM_DB_NAME=AmazefulDev
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ~/Amazeful-Twitch:/home/Amazeful-Twitch
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
